### ISSUE TITLE
Running merlon init after deleting the .merlon folder destroys the /papermario folder

### ISSUE THREAD

**Issue by Pronyo-Chan** [nanaian/merlon#25]
1) Create a new merlon package with merlon new
2) in the new mod folder, run merlon init
3) Delete the .merlon folder
4) Run merlon init again

Result: The papermario folder gets deleted and the following error is printed:

```
fatal: destination path 'papermario' already exists and is not an empty directory.
Error: failed to initialise package test by Pronyo <franktb93@gmail.com>

Caused by:
    failed to clone decomp repository
```

This is a potentially destructive operation if the user had unpushed/unexported changes in the papermario folder

**Comment by nanaian** [comment]
Some thoughts:

1. Don't delete the directory, obviously
2. A better error message - we could ask the user to delete `papermario` if and only if they know their changes are backed up
3. Have `merlon init` work if there is a directory already, and just sync it & create `.merlon`
