### ISSUE TITLE
Project64 version differs

### ISSUE THREAD

**Issue by untuned** [nanaian/merlon#45]
I have installed the latest version of Project64 (which currently is 3.0.1) to a common directory, `C:\Program Files (x86)\Project64 3.0`.
This is an issue as merlon only looks for `2.3.x`.

https://github.com/nanaian/merlon/blob/208303b343d6f9cc84614c4153901e3fc98bae5b/src/emulator.rs#L22-L29

**Comment by nanaian** [comment]
Thanks! I'd appreciate a small PR to fix this, you can edit the file directly in github
